[[redirects]]
  from = "/laurent-chalumeau/"
  to = "/laurent-chalumeau-kif/"
  status = 301
  force = true

[[redirects]]
  from = "/the-national-en-visuel/"
  to = "/the-national-terrible-love/"
  status = 301
  force = true

[[redirects]]
  from = "/histoire-du-cinema-en-2-minutes/"
  to = "/35mm-histoire-du-cinema-en-2-minutes/"
  status = 301
  force = true

[[redirects]]
  from = "/high-violet-haute-voltige/"
  to = "/the-national-high-violet/"
  status = 301
  force = true

[[redirects]]
  from = "/Concours-Katerine-Francis-et-ses"
  to = "/concours-katerine-francis-et-ses-peintres/"
  status = 301
  force = true

[[redirects]]
  from = "/boneless-symphonique/"
  to = "/the-notwist-boneless-version-symphonique/"
  status = 301
  force = true

[[redirects]]
  from = "/prefab-prouuuut/"
  to = "/prefab-sprout-steve-mcqueen/"
  status = 301
  force = true
